{{- if .Values.store.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.store.name }}-mysql
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.store.name }}
    app.kubernetes.io/component: mysql
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql
  selector:
    app.kubernetes.io/name: {{ .Values.store.name }}
    app.kubernetes.io/component: mysql
{{- end }}