{{- if and .Values.store.enabled .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.store.name }}-mysql-netpol
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.store.name }}
    app.kubernetes.io/component: mysql
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.store.name }}
      app.kubernetes.io/component: mysql
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.store.name }}
          app.kubernetes.io/component: wordpress
    ports:
    - protocol: TCP
      port: 3306
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.store.name }}
          app.kubernetes.io/component: setup
    ports:
    - protocol: TCP
      port: 3306
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: UDP
      port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.store.name }}-wordpress-netpol
  namespace: {{ .Values.store.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.store.name }}
    app.kubernetes.io/component: wordpress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.store.name }}
      app.kubernetes.io/component: wordpress
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
    ports:
    - protocol: TCP
      port: 80
  - from:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 80
  egress:
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.store.name }}
          app.kubernetes.io/component: mysql
    ports:
    - protocol: TCP
      port: 3306
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: UDP
      port: 53
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
{{- end }}