{{- if .Values.store.enabled }}
{{- if .Values.mysql.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.store.name }}-mysql-pvc
  namespace: {{ .Release.Namespace }}   # <--- FIXED
  labels:
    app.kubernetes.io/name: {{ .Values.store.name }}
    app.kubernetes.io/component: mysql
spec:
  accessModes:
    - {{ .Values.mysql.persistence.accessMode }}
  storageClassName: {{ .Values.global.storageClass }}
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size }}
{{- end }}
---
{{- if .Values.wordpress.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.store.name }}-wordpress-pvc
  namespace: {{ .Release.Namespace }}   # <--- FIXED
  labels:
    app.kubernetes.io/name: {{ .Values.store.name }}
    app.kubernetes.io/component: wordpress
spec:
  accessModes:
    - {{ .Values.wordpress.persistence.accessMode }}
  storageClassName: {{ .Values.global.storageClass }}
  resources:
    requests:
      storage: {{ .Values.wordpress.persistence.size }}
{{- end }}
{{- end }}